# Generated by Django 3.2.3 on 2021-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username of the person who sent a message', max_length=50, verbose_name='user')),
                ('text', models.CharField(help_text='Text of a messages', max_length=500, verbose_name='text')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of a message', verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
    ]
